#!/bin/bash
# ==============================================================================
# gen_keys.sh — generate all local secrets. NOTHING here is committed.
#   - keys/ecdsa_private.pem / ecdsa_public.pem  (ES256 capability-token signing)
#   - deploy/docker/.env                         (LOG_ENC_KEY_HEX, REMOTE_API_KEY)
#   - secrets/api_keys.json                      (api_key -> principal map)
# Run once before `docker compose up`. Re-run to rotate.
# ==============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

mkdir -p keys secrets deploy/docker

echo "[gen] ES256 keypair..."
openssl ecparam -name prime256v1 -genkey -noout -out keys/ecdsa_private.pem
openssl ec -in keys/ecdsa_private.pem -pubout -out keys/ecdsa_public.pem 2>/dev/null
chmod 600 keys/ecdsa_private.pem

echo "[gen] AES-256 audit-log key + provider key placeholder -> deploy/docker/.env"
LOG_KEY="$(openssl rand -hex 32)"
cat > deploy/docker/.env <<EOF
# Generated by gen_keys.sh — DO NOT COMMIT
LOG_ENC_KEY_HEX=${LOG_KEY}
REMOTE_API_KEY=
EOF

echo "[gen] API keys -> secrets/api_keys.json"
gen() { openssl rand -hex 24; }
K_ANALYST="mcp_$(gen)"; K_AUDITOR="mcp_$(gen)"; K_NETBOT="mcp_$(gen)"; K_ADMIN="mcp_$(gen)"
cat > secrets/api_keys.json <<EOF
{
  "${K_ANALYST}": "principal_analyst",
  "${K_AUDITOR}": "principal_auditor",
  "${K_NETBOT}":  "principal_netbot",
  "${K_ADMIN}":   "principal_admin"
}
EOF
chmod 600 secrets/api_keys.json

echo
echo "==================== SAVE THESE KEYS (shown once) ===================="
echo " analyst : ${K_ANALYST}"
echo " auditor : ${K_AUDITOR}"
echo " netbot  : ${K_NETBOT}"
echo " admin   : ${K_ADMIN}"
echo "====================================================================="
echo "[gen] done. Secrets live under keys/ and secrets/ (both gitignored)."
